name = "GamersAdvanced"
author = "Gamers"
version = "1.4.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "17e4d94e8efec31bd829c8d38c862331309cf73b3c0d6e4759fd68a5d844bbd0"

[versions]
forge = "43.3.5"
minecraft = "1.19.2"

[options]
no-internal-hashes = "true"
