name = "GamersAdvanced"
author = "Gamers"
version = "1.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a4d09c8260d7caed1b63d7e2fd0c4bd761be5cd4bf4ec374807b8ac1d9a47b93"

[versions]
forge = "43.3.5"
minecraft = "1.19.2"

[options]
no-internal-hashes = "true"
