name = "GamersAdvanced"
author = "Gamers"
version = "1.9.HF1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0cc66460678d011effbde2d9ec5c6fd4a28d2148f09025b76cc60b5b620be271"

[versions]
forge = "43.3.7"
minecraft = "1.19.2"

[options]
no-internal-hashes = "true"
