name = "GamersAdvanced"
author = "Gamers"
version = "1.7"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f9f8ad5d7a9ecbfe721b758d496ac26f3cd109ae41a154e1e45904a5b3e0ccff"

[versions]
forge = "43.3.7"
minecraft = "1.19.2"

[options]
no-internal-hashes = "true"
