name = "GamersAdvanced"
author = "Gamers"
version = "1.6.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8ce0246d992d43c4a535fedf3a9ab9389ba08394de60ed279da3f269558f70cc"

[versions]
forge = "43.3.5"
minecraft = "1.19.2"

[options]
no-internal-hashes = "true"
