name = "GamersAdvanced"
author = "Gamers"
version = "1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8db72900ffa2965b3e4c1e706fe33122a251b03ecf62841eb0ef48a99f0a1780"

[versions]
forge = "43.3.5"
minecraft = "1.19.2"

[options]
no-internal-hashes = "true"
