name = "GamersAdvanced"
author = "Gamers"
version = "1.8.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7c251b6693a8240289b42c391eb8811a204a5d6ef49491a8e46ae4f3cd7b1c85"

[versions]
forge = "43.3.7"
minecraft = "1.19.2"

[options]
no-internal-hashes = "true"
