name = "GamersAdvanced"
author = "Gamers"
version = "1.4"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6c2f91b2fb9c3342ca444584bcc1241f54c96ab01cde112110cb6b7f28a16080"

[versions]
forge = "43.3.5"
minecraft = "1.19.2"

[options]
no-internal-hashes = "true"
