name = "GamersAdvanced"
author = "Gamers"
version = "1.1.HF1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "60abeef0dac6fb57b11c02c4108c88d0afeac093480ea05080e5cdc70aa502a4"

[versions]
forge = "43.3.5"
minecraft = "1.19.2"

[options]
no-internal-hashes = "true"
