name = "GamersAdvanced"
author = "Gamers"
version = "1.8.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4a656d9982a5873f49e05704d76d231bb2e8e3bee9bcc9a39e5132532990ac83"

[versions]
forge = "43.3.7"
minecraft = "1.19.2"

[options]
no-internal-hashes = "true"
