name = "GamersAdvanced"
author = "Gamers"
version = "1.3.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5165373f5da37491ae422673cf3a009db486296db380d864a4489634bdf1c4a3"

[versions]
forge = "43.3.5"
minecraft = "1.19.2"

[options]
no-internal-hashes = "true"
