hash-format = "sha256"

[[files]]
file = "config/bcc-common.toml"

[[files]]
file = "config/create-client.toml"

[[files]]
file = "config/fancymenu/config.txt"

[[files]]
file = "config/fancymenu/custom_locals/mod/en_us.local"

[[files]]
file = "config/fancymenu/resources/background.jpg"

[[files]]
file = "config/fancymenu/resources/logo.png"

[[files]]
file = "config/openloader/resources/GamersAdvanced Resources/assets/curios/textures/gui/inventory.png"

[[files]]
file = "config/openloader/resources/GamersAdvanced Resources/pack.mcmeta"

[[files]]
file = "config/quark-common.toml"

[[files]]
file = "config/sanitydim/default.toml"

[[files]]
file = "config/supplementaries-client.toml"

[[files]]
file = "mods/advanced-chimneys.pw.toml"
metafile = true

[[files]]
file = "mods/ae2-things-forge.pw.toml"
metafile = true

[[files]]
file = "mods/applied-energistics-2.pw.toml"
metafile = true

[[files]]
file = "mods/applied-mekanistics.pw.toml"
metafile = true

[[files]]
file = "mods/architectury-api.pw.toml"
metafile = true

[[files]]
file = "mods/attributefix.pw.toml"
metafile = true

[[files]]
file = "mods/auto-leveling.pw.toml"
metafile = true

[[files]]
file = "mods/autoreglib.pw.toml"
metafile = true

[[files]]
file = "mods/ballistix.pw.toml"
metafile = true

[[files]]
file = "mods/beachparty.pw.toml"
metafile = true

[[files]]
file = "mods/better-combat-by-daedelus.pw.toml"
metafile = true

[[files]]
file = "mods/biomes-o-plenty.pw.toml"
metafile = true

[[files]]
file = "mods/botarium.pw.toml"
metafile = true

[[files]]
file = "mods/cc-ballistx.pw.toml"
metafile = true

[[files]]
file = "mods/cc-tweaked.pw.toml"
metafile = true

[[files]]
file = "mods/citadel.pw.toml"
metafile = true

[[files]]
file = "mods/cloth-config.pw.toml"
metafile = true

[[files]]
file = "mods/compressedcreativity.pw.toml"
metafile = true

[[files]]
file = "mods/corgilib.pw.toml"
metafile = true

[[files]]
file = "mods/corpse.pw.toml"
metafile = true

[[files]]
file = "mods/create-big-cannons.pw.toml"
metafile = true

[[files]]
file = "mods/create-crystal-clear.pw.toml"
metafile = true

[[files]]
file = "mods/create-new-age.pw.toml"
metafile = true

[[files]]
file = "mods/create-steam-n-rails.pw.toml"
metafile = true

[[files]]
file = "mods/create.pw.toml"
metafile = true

[[files]]
file = "mods/curios.pw.toml"
metafile = true

[[files]]
file = "mods/do-api.pw.toml"
metafile = true

[[files]]
file = "mods/dynamic-electricity.pw.toml"
metafile = true

[[files]]
file = "mods/electrodynamics.pw.toml"
metafile = true

[[files]]
file = "mods/farmers-delight.pw.toml"
metafile = true

[[files]]
file = "mods/forgeendertech.pw.toml"
metafile = true

[[files]]
file = "mods/framework.pw.toml"
metafile = true

[[files]]
file = "mods/geckolib.pw.toml"
metafile = true

[[files]]
file = "mods/goprone.pw.toml"
metafile = true

[[files]]
file = "mods/iammusicplayer.pw.toml"
metafile = true

[[files]]
file = "mods/idas.pw.toml"
metafile = true

[[files]]
file = "mods/immersive-aircraft.pw.toml"
metafile = true

[[files]]
file = "mods/integrated-api.pw.toml"
metafile = true

[[files]]
file = "mods/iris-flywheel-compat.pw.toml"
metafile = true

[[files]]
file = "mods/kotlin-for-forge.pw.toml"
metafile = true

[[files]]
file = "mods/lets-do-nethervinery.pw.toml"
metafile = true

[[files]]
file = "mods/little-contraptions.pw.toml"
metafile = true

[[files]]
file = "mods/little-logistics.pw.toml"
metafile = true

[[files]]
file = "mods/max-health-fix.pw.toml"
metafile = true

[[files]]
file = "mods/mekanism-additions.pw.toml"
metafile = true

[[files]]
file = "mods/mekanism-generators.pw.toml"
metafile = true

[[files]]
file = "mods/mekanism-tools.pw.toml"
metafile = true

[[files]]
file = "mods/mekanism.pw.toml"
metafile = true

[[files]]
file = "mods/minecraft-comes-alive-reborn.pw.toml"
metafile = true

[[files]]
file = "mods/mrcrayfishs-gun-mod.pw.toml"
metafile = true

[[files]]
file = "mods/mutil.pw.toml"
metafile = true

[[files]]
file = "mods/nuclear-science.pw.toml"
metafile = true

[[files]]
file = "mods/oh-the-biomes-youll-go.pw.toml"
metafile = true

[[files]]
file = "mods/otyacraft-engine.pw.toml"
metafile = true

[[files]]
file = "mods/passive-skill-tree.pw.toml"
metafile = true

[[files]]
file = "mods/patchouli.pw.toml"
metafile = true

[[files]]
file = "mods/playeranimator.pw.toml"
metafile = true

[[files]]
file = "mods/pneumaticcraft-repressurized.pw.toml"
metafile = true

[[files]]
file = "mods/pollution-of-the-realms.pw.toml"
metafile = true

[[files]]
file = "mods/quark.pw.toml"
metafile = true

[[files]]
file = "mods/relics-mod.pw.toml"
metafile = true

[[files]]
file = "mods/repurposed-structures.pw.toml"
metafile = true

[[files]]
file = "mods/sanity-descent-into-madness.pw.toml"
metafile = true

[[files]]
file = "mods/selene.pw.toml"
metafile = true

[[files]]
file = "mods/simply-swords.pw.toml"
metafile = true

[[files]]
file = "mods/sound-physics-remastered.pw.toml"
metafile = true

[[files]]
file = "mods/supplementaries.pw.toml"
metafile = true

[[files]]
file = "mods/terrablender.pw.toml"
metafile = true

[[files]]
file = "mods/tetra.pw.toml"
metafile = true

[[files]]
file = "mods/tough-as-nails.pw.toml"
metafile = true

[[files]]
file = "mods/untamedwilds.pw.toml"
metafile = true

[[files]]
file = "mods/vinery.pw.toml"
metafile = true

[[files]]
file = "mods/welcome-to-meadow.pw.toml"
metafile = true

[[files]]
file = "mods/xaeros-minimap-fair-play-edition.pw.toml"
metafile = true

[[files]]
file = "mods/yungs-api.pw.toml"
metafile = true

[[files]]
file = "mods/yungs-better-desert-temples.pw.toml"
metafile = true

[[files]]
file = "mods/yungs-better-dungeons.pw.toml"
metafile = true

[[files]]
file = "mods/yungs-better-end-island.pw.toml"
metafile = true

[[files]]
file = "mods/yungs-better-jungle-temples.pw.toml"
metafile = true

[[files]]
file = "mods/yungs-better-mineshafts-forge.pw.toml"
metafile = true

[[files]]
file = "mods/yungs-better-nether-fortresses.pw.toml"
metafile = true

[[files]]
file = "mods/yungs-better-strongholds.pw.toml"
metafile = true

[[files]]
file = "mods/yungs-better-witch-huts.pw.toml"
metafile = true

[[files]]
file = "mods/yungs-bridges.pw.toml"
metafile = true

[[files]]
file = "mods/yungs-extras.pw.toml"
metafile = true
