name: Release
on:
  release:
    types: [created]

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Merge beta to release
        run: |
          git checkout release
          git merge beta
          git push origin release
